#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Sep 17 13:02:18 CST 2020
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto b54b6fbaa8e3457aad7350bdff455d43 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L secureip --snapshot system_tb_func_synth xil_defaultlib.system_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto b54b6fbaa8e3457aad7350bdff455d43 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L secureip --snapshot system_tb_func_synth xil_defaultlib.system_tb xil_defaultlib.glbl -log elaborate.log

